Update patch set 3
Patch Set 3: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset merges but does not build in AOSP.
The following snippet of `make` output may point you in the right direction:

  packages/providers/TelephonyProvider/src/com/android/providers/telephony/SmsProvider.java:42: cannot find symbol
symbol  : class SubscriptionController
location: package android.telephony
import android.telephony.SubscriptionController;
                        ^
packages/providers/TelephonyProvider/src/com/android/providers/telephony/SmsProvider.java:43: package android.telephony.SubscriptionController does not exist
import android.telephony.SubscriptionController.SubInfoRecord;
                                               ^
packages/providers/TelephonyProvider/src/com/android/providers/telephony/TelephonyProvider.java:37: cannot find symbol
...


If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 3
Label: Verified=-1